### PR TITLE
✨ Parse command line flags for the placement controller

### LINKED ISSUE #62: Add cobra lib to placement controller main to parse flags and start command
This issue is related to #61 - we should follow the pattern used in the kcp core (see for example https://github.com/kcp-dev/kcp/tree/main/cmd/syncer to parse flags and start the command)

### PR DESCRIPTION
**Pull request by waltforme**
Closes #62

### CODE REVIEW

**Comment by clubanderson** [comment]
@waltforme please rebase now that makefile and codegen are working

**Comment by waltforme** [comment]
> @waltforme , @clubanderson : do you guys know about `git rebase`?

I was lazy enough waiting for `main` to finalize its recent big changes so that I can do a one-shot rebase instead of following `main` closely. Now it is done. Thanks for the reminder! @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
My earlier comment was about https://git-scm.com/book/en/v2/Git-Branching-Rebasing#_rebase_vs_merge .  You guys are doing the opposite of what Kubernetes requires, which is that each PR uses a branch that simply diverges from some commit in the main branch.

**Pull request merged**
