### PR TITLE
✨ Update boilerplate.go.txt

### PR DESCRIPTION
**Pull request by clubanderson**
update kcp with KubeStellar

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
There is more than one boilerplate file.

**Comment by clubanderson** [comment]
@MikeSpreitzer all .go files have been updated - please review

**Comment by clubanderson** [comment]
fixed the dummies and declarations files to please PROW

**Review by MikeSpreitzer — COMMENTED** [review]
/lgtm

**Pull request merged**
