### PR TITLE
🐛 Manually add plural form names for SinglePlacementSlice

### PR DESCRIPTION
**Pull request by waltforme**
## Summary
This is a _temporary_ fix to #174.

With the plural form names _manually_ written to SinglePlacementSlice's CRD and APIResourceSchema, access to singleplacementslices are back to normal.

kubectl:
```
👉 edge-mc $ kc get singleplacementslices
NAME        AGE
hardcoded   104s
👉 edge-mc $ kc get singleplacementslice
NAME        AGE
hardcoded   106s
```

Programmatic:
```
I0220 15:15:31.493378   45159 controller.go:339] "created SinglePlacementSlice" reconciler="edge-scheduler" key="kvdk2spgmbix|test-1" edgeplacement.workspace="kvdk2spgmbix" edgeplacement.namespace="" edgeplacement.name="test-1" edgeplacement.apiVersion="" name="hardcoded" workspace="kvdk2spgmbix"
```

This PR is only a temporary fix to #174, because
- `make crds` reverts all changes here in this PR;
-  file**names** (not file contents) for the CRD and the APIResourceSchema still use singular form.

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
I am not sure this is the right fix.
Why is https://github.com/kcp-dev/kcp/blob/c4a476cbd525a59b79bb0235d82ce0c2624702d7/config/crds/apis.kcp.io_apiexportendpointslices.yaml#L16 right?

**Comment by waltforme** [comment]
> I am not sure this is the right fix.
> 
> Having something that is overwritten by regular operations is not good.
> 
> Why is https://github.com/kcp-dev/kcp/blob/c4a476cbd525a59b79bb0235d82ce0c2624702d7/config/crds/apis.kcp.io_apiexportendpointslices.yaml#L16 correct?

I guess everyone knows it is not the right fix and it is not good.

I think the question we should ask it, why our lines are wrong? But I don't know the answer. Otherwise I would fix it in the right way.

**Comment by MikeSpreitzer** [comment]
Looks like you found the right fix in #178

**Comment by ezrasilvera** [comment]
@waltforme So can this be closed after https://github.com/kcp-dev/edge-mc/pull/178 was merged?

**Comment by waltforme** [comment]
> Looks like you found the right fix in #178

Yes, thanks for reviewing #178.

**Comment by waltforme** [comment]
> @waltforme So can this be closed after #178 was merged?

Sure, let me do it.

**Pull request closed without merging**
