### PR TITLE
:bug: updated api-gen call to include repo_root

### LINKED ISSUE #140: feature: `make crds` should include APIExport generation
### Feature Description

edge-mc should have the functional equivalent of https://github.com/kcp-dev/kcp/blob/cb8dd3c46470f30414c6789be956162ccb21f669/hack/update-codegen-crds.sh#L55-L58 --- ideally without maintaining a copy of the apigen tool.

### Proposed Solution

Have the Makefile or a script `go install github.com/kcp-dev/kcp/cmd/apigen@$right_version` into some tools binary directory and invoke it from there.  https://github.com/kcp-dev/kcp/pull/2669 has merged and this makes it possible to `go install` apigen.

I just tested the apigen from kcp commit cb8dd3c46470f30414c6789be956162ccb21f669 and it produced exactly the same output as the apigen binary that I built earlier from kcp commit 4506fdc06406 (which is the one that edge-mc currently depends on).

### Alternative Solutions

- Maintain a copy of the apigen source.
- Have the Makefile or script `git clone` kcp to get the source and then build it.

### Want to contribute?

- [x] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by clubanderson**
## Related issue(s)

Fixes #140

### CODE REVIEW

**Comment by clubanderson** [comment]
without REPO_ROOT make crds target fails

**Comment by clubanderson** [comment]
@MikeSpreitzer did you 'make tools' first?

**Comment by clubanderson** [comment]
/retitle :bug: updated api-gen call to include repo_root

**Comment by MikeSpreitzer** [comment]
I did not `make tools` first.  It looks like the Makefile tries to pre-req the relevant tools but overlooks one:
```
crds: $(CONTROLLER_GEN) $(YAML_PATCH)
	./hack/update-codegen-crds.sh
.PHONY: crds
```

**Pull request closed without merging**
