### PR TITLE
:bug: re-added hack/verify-contextual-logging.sh back to makefile

### PR DESCRIPTION
**Pull request by clubanderson**
re-added hack/verify-contextual-logging.sh back to makefile

## Summary
re-added hack/verify-contextual-logging.sh back to makefile

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
@MikeSpreitzer please approve

**Comment by clubanderson** [comment]
@MikeSpreitzer generated files removed and logcheck.out is clean.

**Review by MikeSpreitzer — APPROVED** [review]
This looks like progress.
/LGTM

**Review by MikeSpreitzer — CHANGES_REQUESTED** [review]
It looks like "logcheck: ./... matched no packages" needs to remain in logcheck.out

**Pull request merged**
