### PR TITLE
✨ Refinements wrt SetBinder, main

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR adds a little more commentary and type definitions showing what I expect to be the internal structure of a SetBinder.  I introduced some more generic abstractions that seemed relevant, and revised some existing ones for more consistency.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
@ezrasilvera can you give this a review to unblock @MikeSpreitzer

**Comment by clubanderson** [comment]
@waltforme please spend some time reviewing this PR for Mike

**Comment by MikeSpreitzer** [comment]
Remember that #245 builds on this (i.e., revises and extends this).  Could we please get this merged?

**Pull request merged**
