### PR TITLE
:book: Make edge-syncer.md executable doc

### PR DESCRIPTION
**Pull request by yana1205**
## Summary

I made edge-syncer.md executable doc.

The updated edge-syncer.md will look like this: https://yana1205.github.io/edge-mc/doc-test/Coding%20Milestones/PoC2023q1/edge-syncer/

Doc shells for syncer e2e ran and completed successfully (The run result: https://github.com/yana1205/edge-mc/actions/runs/5217541993/jobs/9417478356)

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by yana1205** [comment]
I will rebase this branch once https://github.com/kcp-dev/edge-mc/pull/581 is merged. Hold to merge.

**Comment by clubanderson** [comment]
This is excellent. We have a prow issue holding up the other issue. I should have that cleared in the morning. Thank you for putting this together. Was it difficult to do?  What's your feedback?

**Comment by yana1205** [comment]
No. I could easily work with doc-execute framework. It help me to reduce manual validation.  

I am heavily using this command (`make MANIFEST="'content/Coding Milestones/PoC2023q1/edge-syncer.md'" docs-ecutable`) at local. This is specific to me but it may be helpful to add generated files during doc-execute to .gitignore (or working directory for docs-ecutable). I manually clean them up to avoid accidentally including them in a commit.
Thanks for developing this helpful tool.

**Comment by clubanderson** [comment]
Oh. I see. So you were using this to iterate. I can mask off the generated files and the other sub dirs from the checkout. Great feedback @yana1205

**Comment by clubanderson** [comment]
forcing merge because build system is broken on go.mod.  Since this is only documentation, I am granting it a pass.

**Review by clubanderson — APPROVED** [review]

**Pull request merged**
