### PR TITLE
🐛 Factor ESPW setup out of `kubestellar start`

### LINKED ISSUE #401: bug: ESPW create/delete should be bundled with install/uninstall not start/stop
### Describe the bug

In common Uniix/Linux packages, starting and stopping the daemons does not create/delete the supporting state (e.g., files in /etc).  We should follow the usual pattern.

### Steps To Reproduce

read the doc or experiment

### Expected Behaviour

Unsurprising bundling of behavior

### Additional Context

_No response_

### LINKED ISSUE #402: bug: bootstrap decides whether to `kubestellar start` based ONLY on controllers
### Describe the bug

bootstrap-kubestellar decides whether to invoke `kubestellar start` based ONLY on whether the controllers are all running --- not considering whether the ESPW exists.  Yet `kubestellar start` is what establishes the ESPW (which is a bug, see #401).

Consequently, a user who has the controllers running but no ESPW will get a broken install from bootstrap-kubestellar.

### Steps To Reproduce

See above.

### Expected Behaviour

No inappropriate bundling.  No confusion from bundling.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR separates ESPW setup from `kubestellar start`, into a new subcommand `kubestellar init`.

This PR also removes some inappropriate precondition checking: for docker and for go version.

## Related issue(s)

Fixes #401
Fixes #402 

/cc @dumb0002 
/cc @francostellari 
/cc @clubanderson 
@eaepstein

### CODE REVIEW

**Comment by dumb0002** [comment]
@MikeSpreitzer, to solve this issue I proposed the following:

  1 - Update  `kubestellar`  with the following flags (similar to  Linux `systemctl`  command): start | stop | restart
          a) start - flag checks if the kubestellar controllers are already running and does nothing if they are already running

  2 - `bootstrap-kubestellar.sh`: does not need to check if the kubestellar are running but it does the following:
           a) create espw
          b)  delete espw
          c) check if espw already exists
          d) check if kcp is running and so ...

In the way, we clearly separate the functionality for both scripts `kubestellar`  and ` bootstrap-kubestellar.sh` - each of them only checks and deletes the components that they are responsible for.

**Comment by MikeSpreitzer** [comment]
@dumb0002 : I think we do not want to put more functionality than necessary into the script that we are telling people to curl directly to bash.  Many people simply refuse to do that, and will at least read the script before doing that.  And regular usage will not do that, we are only talking about a special thing for the quickstart.  So I think the ESPW creation belongs in an executable in `bin`.  I am OK with bundling ESPW deletion with a broader uninstall command (also in an executable in `bin`).

**Comment by dumb0002** [comment]
@MikeSpreitzer, Yes, we can keep the ESPW setup into in an executable in bin indeed.  However, scripts like `kubestellar` will be used by both user and developer persona.  The developer may not need to run `bootstrap-kubestellar.sh` to build his development environment. The developer may start the kcp server from a cloned repo and jump directly to use the `kubestellar start` script only. Others functionalities like `kubestellar start | stop| restart` will be useful for that persona. Otherwise, we may need to write another  kubestellar like script for the developer persona. I am ok with that as long as we decide that this is the design that we are going to target.

**Comment by MikeSpreitzer** [comment]
@dumb0002 : for the contributor, indeed we do not expect them to run bootstrap-kubestellar --- that is specifically designed for the assumption that a `git clone` is NOT being used.

I am OK with refactoring the current start (which is really stop-then-start) and stop into start, restart, and stop.  That would align better with expectations for a systemd service, which is a familiar management paradigm in Linux.

**Comment by MikeSpreitzer** [comment]
I am closing this PR in favor of #408 and #409, for the sake of evolutionary discipline.
These do not attempt to refactor `restart` out of `start`, that can be additional PR(s).

**Pull request closed without merging**
