### PR TITLE
🌱 Use Go 1.19

### PR DESCRIPTION
**Pull request by waltforme**

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
I get a failure:

```
(base) mspreitz@mjs12 edge-mc % make build-all
GOOS=darwin GOARCH=amd64 /Library/Developer/CommandLineTools/usr/bin/make build WHAT='./cmd/...  ./tmc/cmd/...'
hack/verify-go-versions.sh
Wrong go version in .github/workflows/*.yaml, expected 1.19
make[1]: *** [verify-go-versions] Error 1
make: *** [build-all] Error 2
```

**Comment by waltforme** [comment]
`hack/verify-go-versions.sh` contains go version check against CONTRIBUTION.md which is a good thing. So I made CONTRIBUTION.md compliant with the check.

**Comment by MikeSpreitzer** [comment]
Good improvement on CONTRIBUTING.md.
But `make build` still fails.

**Comment by waltforme** [comment]
> Good improvement on CONTRIBUTING.md. But `make build` still fails.

The only missing part is now from the yaml files for GH Actions. I saw it is already assigned to @clubanderson in #116, so I didn't touch it. But we can bypass this by insert `go-version: v1.19` to somewhere in one of the yamls, and got `make build-all` returns 0. @MikeSpreitzer

**Review by clubanderson — APPROVED** [review]

**Pull request merged**
