### PR TITLE
Docs: Update CONTRIBUTING.md regarding golang pre-req version

### PR DESCRIPTION
**Pull request by fileppb**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by fileppb** [comment]
fixes issue #231

**Comment by clubanderson** [comment]
/lgtm
@MikeSpreitzer can you approve?

**Comment by fileppb** [comment]
@clubanderson @MikeSpreitzer can you reapply the /lgtm tag and approve? 
I realized belatedly that the kcp/.github/workflows yaml files go-version fields also need to agree with go.mod, so I made a change to include that info.
I also submitted this issue to kcp-dev: https://github.com/kcp-dev/kcp/issues/2904

**Pull request merged**
