### PR TITLE
✨ Yet more placement translator development

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
It is mostly working now.

## Related issue(s)

Fixes #

/cc @yana1205 
/cc @waltforme

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
The force-push to 97ab535c was the promised rebase onto `main`.

**Comment by yana1205** [comment]
/lgtm

Thank you very much. With this PlacementTranslator, Kyverno workloads deployed to workload management workspace (wmw) are successfully propagated to each mailbox workspaces, expected SyncerConfig is created there, and then the latest Edge Syncer successfully consumed it and synced between a mailbox workspace and an edge cluster.

Findings:
- The generated SyncerConfig contains some kcp/edge-mc unique resources. Is it better to exclude them because edge cluster does not have kcp/edge-mc resources? Though, it's no problem if they are in SyncerConfig.
    ```
    namespaceScope:
    ...
        - apiVersion: v1alpha1
          group: edge.kcp.io
          resource: customizers
    clusterScope:
    ...
      - apiVersion: v1alpha1
        group: apis.kcp.io
        objects:
        - bind-kube
        resource: apibindings
    ```

**Comment by MikeSpreitzer** [comment]
The latest revision has more bug fixing, and the placement translator is working better now.

```console
$ go run -race ./cmd/placement-translator -v=4 &> /tmp/o.txt
^C

$ grep -iE "object.*mailbox" /tmp/o.txt
I0416 02:26:14.473127   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=3 objectRef={cluster:cr0z2k4a52elidbr groupResource:{Group:apis.kcp.io Resource:apibindings} namespace:no NS name:bind-kube} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-g SyncTargetName:sync-target-g SyncTargetUID:cec76460-7066-4c7e-b856-74bf8f4d3e98}
I0416 02:26:14.527076   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=0 objectRef={cluster:cr0z2k4a52elidbr groupResource:{Group: Resource:configmaps} namespace:specialstuff name:httpd-htdocs} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-g SyncTargetName:sync-target-g SyncTargetUID:cec76460-7066-4c7e-b856-74bf8f4d3e98}
I0416 02:26:14.705809   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=1 objectRef={cluster:comydvfkf8q802yi groupResource:{Group: Resource:configmaps} namespace:commonstuff name:httpd-htdocs} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-g SyncTargetName:sync-target-g SyncTargetUID:cec76460-7066-4c7e-b856-74bf8f4d3e98}
E0416 02:26:14.857461   22645 workload-projector.go:800] "Failed to create object in mailbox workspace" err="apibindings.apis.kcp.io \"bind-kube\" already exists" worker=2 objectRef={cluster:comydvfkf8q802yi groupResource:{Group:apis.kcp.io Resource:apibindings} namespace:no NS name:bind-kube} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-g SyncTargetName:sync-target-g SyncTargetUID:cec76460-7066-4c7e-b856-74bf8f4d3e98}
I0416 02:26:15.812193   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=1 objectRef={cluster:comydvfkf8q802yi groupResource:{Group: Resource:configmaps} namespace:commonstuff name:httpd-htdocs} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-f SyncTargetName:sync-target-f SyncTargetUID:c49209fe-abf4-4427-868d-ce63dd5198d2}
I0416 02:26:15.869235   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=2 objectRef={cluster:comydvfkf8q802yi groupResource:{Group:apis.kcp.io Resource:apibindings} namespace:no NS name:bind-kube} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-f SyncTargetName:sync-target-f SyncTargetUID:c49209fe-abf4-4427-868d-ce63dd5198d2}
I0416 02:26:15.966182   22645 workload-projector.go:781] "No need to update object in mailbox workspace" worker=1 objectRef={cluster:comydvfkf8q802yi groupResource:{Group:apis.kcp.io Resource:apibindings} namespace:no NS name:bind-kube} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-g SyncTargetName:sync-target-g SyncTargetUID:cec76460-7066-4c7e-b856-74bf8f4d3e98}
I0416 02:26:15.969809   22645 workload-projector.go:781] "No need to update object in mailbox workspace" worker=1 objectRef={cluster:comydvfkf8q802yi groupResource:{Group:apis.kcp.io Resource:apibindings} namespace:no NS name:bind-kube} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-f SyncTargetName:sync-target-f SyncTargetUID:c49209fe-abf4-4427-868d-ce63dd5198d2}
I0416 02:26:16.153188   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=0 objectRef={cluster:cr0z2k4a52elidbr groupResource:{Group:apps Resource:deployments} namespace:specialstuff name:speciald} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-g SyncTargetName:sync-target-g SyncTargetUID:cec76460-7066-4c7e-b856-74bf8f4d3e98}
I0416 02:26:16.186953   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=3 objectRef={cluster:comydvfkf8q802yi groupResource:{Group:apps Resource:deployments} namespace:commonstuff name:commond} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-g SyncTargetName:sync-target-g SyncTargetUID:cec76460-7066-4c7e-b856-74bf8f4d3e98}
I0416 02:26:17.282608   22645 workload-projector.go:803] "Created object in mailbox workspace" worker=3 objectRef={cluster:comydvfkf8q802yi groupResource:{Group:apps Resource:deployments} namespace:commonstuff name:commond} destination={Cluster:2i5tt9bl6jmw7wit LocationName:location-f SyncTargetName:sync-target-f SyncTargetUID:c49209fe-abf4-4427-868d-ce63dd5198d2}
```

@yana1205 : the latest revision should remove those resources from the SyncerConfig.

**Comment by yana1205** [comment]
Thanks. The latest one is working for the Kyverno case too.

/lgtm

**Pull request merged**
