### PR TITLE
:sparkles: Fresh start on mailbox controller

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR makes a fresh start on the mailbox controller, because #67 appears to be terminally wedged.

At this very early stage of development, this controller only creates informers on all SyncTargets and on Workspaces that are in a given workspace and logs what those informers report.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
@MikeSpreitzer followed your instructions with 0.10.0 of kcp binary.  I got the following

```
go run ./cmd/mailbox-controller/main.go -v=2
I0127 09:56:50.585889   40907 main.go:192] "Pause because APIExport not found" exportName="workload.kcp.io"
```

please advise

**Comment by clubanderson** [comment]
```
k get --context root APIExport     

NAME                     AGE
apiresource.kcp.dev      118d
scheduling.kcp.dev       118d
shards.tenancy.kcp.dev   118d
tenancy.kcp.dev          118d
topology.kcp.dev         15m
workload.kcp.dev         118d
```

**Comment by clubanderson** [comment]
```
kcp --version                             
kcp version v1.24.3+kcp-v0.10.0
```

**Comment by MikeSpreitzer** [comment]
@clubanderson : If you use `-v=8` or more verbose on the mailbox controller then you will get more details that should be revealing.

**Comment by clubanderson** [comment]
its looking for workload.kcp.io and I have workload.kcp.dev - does that make a difference?

```
go run ./cmd/mailbox-controller/main.go -v=8
I0127 11:20:03.278696   43383 loader.go:372] Config loaded from file:  /Users/andan02/.kcp/admin.kubeconfig
I0127 11:20:03.279239   43383 round_trippers.go:463] GET https://192.168.4.150:6443/clusters/root/apis/apis.kcp.io/v1alpha1/apiexports/workload.kcp.io
I0127 11:20:03.279250   43383 round_trippers.go:469] Request Headers:
I0127 11:20:03.279284   43383 round_trippers.go:473]     Accept: application/json, */*
I0127 11:20:03.279297   43383 round_trippers.go:473]     User-Agent: mailbox-controller
I0127 11:20:03.279305   43383 round_trippers.go:473]     Authorization: Bearer <masked>
I0127 11:20:03.285373   43383 round_trippers.go:574] Response Status: 404 Not Found in 6 milliseconds
I0127 11:20:03.285393   43383 round_trippers.go:577] Response Headers:
I0127 11:20:03.285401   43383 round_trippers.go:580]     Audit-Id: 8672319f-081b-4496-b8da-3f4b82b18b02
I0127 11:20:03.285412   43383 round_trippers.go:580]     Cache-Control: no-cache, private
I0127 11:20:03.285427   43383 round_trippers.go:580]     Content-Type: text/plain; charset=utf-8
I0127 11:20:03.285467   43383 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0127 11:20:03.285479   43383 round_trippers.go:580]     Content-Length: 19
I0127 11:20:03.285485   43383 round_trippers.go:580]     Date: Fri, 27 Jan 2023 16:20:03 GMT
I0127 11:20:03.285536   43383 request.go:1073] Response Body: 404 page not found
I0127 11:20:03.285595   43383 main.go:192] "Pause because APIExport not found" exportName="workload.kcp.io"
I0127 11:20:18.286228   43383 round_trippers.go:463] GET https://192.168.4.150:6443/clusters/root/apis/apis.kcp.io/v1alpha1/apiexports/workload.kcp.io
```

**Comment by MikeSpreitzer** [comment]
Are you running commit 4506fdc06406 of kcp?

**Comment by MikeSpreitzer** [comment]
@clubanderson : you need to run this together with the version of kcp that is documented in go.mod.

**Comment by clubanderson** [comment]
aside from the kcp and kubectl plugin config and execution delay, your mailbox controller appears to work here.  The workspace gets recreated on delete from cmd line, the workspace is remove after deletion of the synctarget.  It has the makings of a mailbox.  
/lgtm

**Pull request merged**
