### PR TITLE
🐛Fix326

### LINKED ISSUE #326: bug: workload not as expected cleaned from edge cluster
### Describe the bug

It seems that the workload running on an edge cluster is not cleaned when the corresponding mailbox is emptied.

Environment:
- kcp v0.11.0
- edge-mc: e796162ebd24cba985d96467e6ffa957ccaf4a46
- syncer image: quay.io/kcpedge/syncer:dev-2023-04-18

### Steps To Reproduce

I used the manifests in https://github.com/edge-experiments/gitops-source/tree/main/edge-mc to produce/reproduce the bug. Detailed as follows.

### Inventory management workspace
In an inventory management workspace, create
- two locations using https://github.com/edge-experiments/gitops-source/blob/main/edge-mc/locations/locations.yaml
- two synctargets using https://github.com/edge-experiments/gitops-source/blob/main/edge-mc/synctargets/synctargets.yaml

In the same inventory management workspace, delete the `default` location.

Locations and synctargets in the Inventory management workspace looks like this:
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get location,synctarget
NAME                                RESOURCE      AVAILABLE   INSTANCES   LABELS   AGE
location.scheduling.kcp.io/aisle1   synctargets   0           1                    5h1m
location.scheduling.kcp.io/aisle2   synctargets   0           1                    5h1m

NAME                                  AGE
synctarget.workload.kcp.io/cluster1   5h
synctarget.workload.kcp.io/cluster2   5h
```
There is a 1:1 relationship between locations and synctargets above: `aisle1` selects `cluster1` and `aisle2` selects `cluster2`.

### Edge clusters
Create 2 kind clusters 'cluster1' and 'cluster2', and installed edge syncers.

### Edge service provider workspace
Setup it in the same way as documented in [example1](https://github.com/kcp-dev/edge-mc/blob/main/docs/content/en/docs/Coding%20Milestones/PoC2023q1/example1.md).

After the setup, CRDs and APIExports in the edge service provider workspace looks like this:
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl ws root:espw
Current workspace is "root:espw".
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get crds,apiexports
NAME                                                                              CREATED AT
customresourcedefinition.apiextensions.k8s.io/apiresources.meta.kcp.io            2023-04-20T03:20:38Z
customresourcedefinition.apiextensions.k8s.io/customizers.edge.kcp.io             2023-04-20T03:20:38Z
customresourcedefinition.apiextensions.k8s.io/edgeplacements.edge.kcp.io          2023-04-20T03:20:38Z
customresourcedefinition.apiextensions.k8s.io/edgesyncconfigs.edge.kcp.io         2023-04-20T03:20:38Z
customresourcedefinition.apiextensions.k8s.io/singleplacementslices.edge.kcp.io   2023-04-20T03:20:38Z
customresourcedefinition.apiextensions.k8s.io/syncerconfigs.edge.kcp.io           2023-04-20T03:20:38Z

NAME                                AGE
apiexport.apis.kcp.io/edge.kcp.io   41h
apiexport.apis.kcp.io/meta.kcp.io   41h
```

### Workload management workspace
Create a workspace as the WMW, then install the apibindings in the same way as documented in [example1](https://github.com/kcp-dev/edge-mc/blob/main/docs/content/en/docs/Coding%20Milestones/PoC2023q1/example1.md). That is, we should manually create two apibindings `bind-espw` and `bind-kube`:
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl ws root:my-org:wmw-turbo
Current workspace is "root:my-org:wmw-turbo".
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get apibindings
NAME                       AGE
apiresource.kcp.io-2ah1m   26h
bind-espw                  4h31m
bind-kube                  4h31m
scheduling.kcp.io-29jyl    26h
tenancy.kcp.io-5s2if       26h
topology.kcp.io-6rvd3      26h
workload.kcp.io-9i8h1      26h
```

In the WMW, create a Namespace `optimized` using https://github.com/edge-experiments/gitops-source/blob/main/edge-mc/namespaces/namespaces.yaml

In the WMW, create a Deployment using kubectl apply -k edge-mc/workloads/cpumemload/
Here we need kustomization to make it work:
```shell
git clone https://github.com/edge-experiments/gitops-source.git 
cd gitops-source
kubectl apply -k edge-mc/workloads/cpumemload/
```

In the WMW, create an EdgePlacement using https://github.com/edge-experiments/gitops-source/blob/main/edge-mc/placements/edgeplacements.yaml

### Workloads on cluster1
The edgeplacement object, when created, selects location `aisle1`. So we can see the workload being delivered to edge cluster1.

```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get ns
NAME                                STATUS   AGE
argocd                              Active   190d
default                             Active   192d
kcp-edge-syncer-cluster1-1ek2thys   Active   109m
kube-node-lease                     Active   192d
kube-public                         Active   192d
kube-system                         Active   192d
local-path-storage                  Active   192d
optimized                           Active   107m
turbonomic                          Active   190d
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl -n optimized get deploy
NAME        READY   UP-TO-DATE   AVAILABLE   AGE
cpu-usage   1/1     1            1           4m28s
```

Correspondingly, we can check the mailbox for the syncer config and the workloads.
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl ws root:espw
Current workspace is "root:espw".
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get Workspace -o "custom-columns=NAME:.metadata.name,SYNCTARGET:.metadata.annotations['edge\.kcp\.io/sync-target-name']"
NAME                                                       SYNCTARGET
kvtwgwtegxp72b72-mb-4f3b272b-0ded-4d02-bae6-bb186689b3e4   cluster2
kvtwgwtegxp72b72-mb-8efe1aeb-d0bd-4f2c-a48b-d955f33ed002   cluster1
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl ws root:espw:kvtwgwtegxp72b72-mb-8efe1aeb-d0bd-4f2c-a48b-d955f33ed002
Current workspace is "root:espw:kvtwgwtegxp72b72-mb-8efe1aeb-d0bd-4f2c-a48b-d955f33ed002".
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get syncerconfig the-one -oyaml && kubectl get ns,deployment -A
apiVersion: edge.kcp.io/v1alpha1
kind: SyncerConfig
metadata:
  annotations:
    kcp.io/cluster: 3597eq3gqxel82mx
  creationTimestamp: "2023-04-21T15:34:17Z"
  generation: 31
  name: the-one
  resourceVersion: "4150"
  uid: 36c0166e-e21c-4379-a63d-ce928575a058
spec:
  namespaceScope:
    namespaces:
    - optimized
    resources:
    - apiVersion: v1
      group: apps
      resource: deployments
    - apiVersion: v1
      group: ""
      resource: limitranges
    - apiVersion: v1
      group: networking.k8s.io
      resource: ingresses
    - apiVersion: v1
      group: ""
      resource: serviceaccounts
    - apiVersion: v1
      group: ""
      resource: resourcequotas
    - apiVersion: v1
      group: ""
      resource: configmaps
    - apiVersion: v1
      group: ""
      resource: secrets
    - apiVersion: v1
      group: coordination.k8s.io
      resource: leases
    - apiVersion: v1
      group: ""
      resource: pods
    - apiVersion: v1
      group: ""
      resource: services
    - apiVersion: v1
      group: rbac.authorization.k8s.io
      resource: roles
    - apiVersion: v1
      group: rbac.authorization.k8s.io
      resource: rolebindings
status: {}
NAME                  STATUS   AGE
namespace/default     Active   5h41m
namespace/optimized   Active   109m

NAMESPACE   NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
optimized   deployment.apps/cpu-usage   0/1     0            0           5m57s
```

### Try to move workloads to cluster2
We can `kubectl edit` the edgeplacement, to change its `locationSelectors`, from
```
      aisle: "1"
```
to
```
      aisle: "2"
```

We can observe the singleplacementslice before and after the `kubectl edit`.
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get sps optimized -oyaml
apiVersion: edge.kcp.io/v1alpha1
destinations:
- cluster: kvtwgwtegxp72b72
  locationName: aisle1
  syncTargetName: cluster1
  syncTargetUID: 8efe1aeb-d0bd-4f2c-a48b-d955f33ed002
kind: SinglePlacementSlice
metadata:
  annotations:
    kcp.io/cluster: 506rmr5eggyb9ukx
  creationTimestamp: "2023-04-21T21:09:26Z"
  generation: 1
  name: optimized
  ownerReferences:
  - apiVersion: edge.kcp.io/v1alpha1
    kind: EdgePlacement
    name: optimized
    uid: c59be5b7-9679-4a60-973e-750aee7867e9
  resourceVersion: "4147"
  uid: c3f99d43-d196-4c18-9828-1ea19a8efd1f
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl edit epl optimized
edgeplacement.edge.kcp.io/optimized edited
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get sps optimized -oyaml
apiVersion: edge.kcp.io/v1alpha1
destinations:
- cluster: kvtwgwtegxp72b72
  locationName: aisle2
  syncTargetName: cluster2
  syncTargetUID: 4f3b272b-0ded-4d02-bae6-bb186689b3e4
kind: SinglePlacementSlice
metadata:
  annotations:
    kcp.io/cluster: 506rmr5eggyb9ukx
  creationTimestamp: "2023-04-21T21:09:26Z"
  generation: 2
  name: optimized
  ownerReferences:
  - apiVersion: edge.kcp.io/v1alpha1
    kind: EdgePlacement
    name: optimized
    uid: c59be5b7-9679-4a60-973e-750aee7867e9
  resourceVersion: "4230"
  uid: c3f99d43-d196-4c18-9828-1ea19a8efd1f
```

We can check the workload being created on cluster2.
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get ns
NAME                                STATUS   AGE
argocd                              Active   190d
default                             Active   192d
kcp-edge-syncer-cluster2-rjx4hkkf   Active   116m
kube-node-lease                     Active   192d
kube-public                         Active   192d
kube-system                         Active   192d
local-path-storage                  Active   192d
optimized                           Active   107m
quotatest                           Active   167d
turbonomic                          Active   190d
kubuntu@ip-172-31-31-125:~/edge-mc$ kubectl -n optimized get deploy
NAME        READY   UP-TO-DATE   AVAILABLE   AGE
cpu-usage   1/1     1            1           103s
```
Correspondingly, we can check the mailbox for the syncer config and the workloads.
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl ws root:espw:kvtwgwtegxp72b72-mb-4f3b272b-0ded-4d02-bae6-bb186689b3e4
Current workspace is "root:espw:kvtwgwtegxp72b72-mb-4f3b272b-0ded-4d02-bae6-bb186689b3e4".
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get syncerconfig the-one -oyaml && kubectl get ns,deployment -A
apiVersion: edge.kcp.io/v1alpha1
kind: SyncerConfig
metadata:
  annotations:
    kcp.io/cluster: 2rxu619y3p9hzg98
  creationTimestamp: "2023-04-21T15:39:51Z"
  generation: 15
  name: the-one
  resourceVersion: "4231"
  uid: f27b1b95-419b-4f64-9ae9-4cc9cf7e19ba
spec:
  namespaceScope:
    namespaces:
    - optimized
    resources:
    - apiVersion: v1
      group: networking.k8s.io
      resource: ingresses
    - apiVersion: v1
      group: ""
      resource: pods
    - apiVersion: v1
      group: ""
      resource: resourcequotas
    - apiVersion: v1
      group: ""
      resource: configmaps
    - apiVersion: v1
      group: apps
      resource: deployments
    - apiVersion: v1
      group: rbac.authorization.k8s.io
      resource: roles
    - apiVersion: v1
      group: ""
      resource: limitranges
    - apiVersion: v1
      group: coordination.k8s.io
      resource: leases
    - apiVersion: v1
      group: ""
      resource: secrets
    - apiVersion: v1
      group: ""
      resource: serviceaccounts
    - apiVersion: v1
      group: ""
      resource: services
    - apiVersion: v1
      group: rbac.authorization.k8s.io
      resource: rolebindings
status: {}
NAME                  STATUS   AGE
namespace/default     Active   5h48m
namespace/optimized   Active   109m

NAMESPACE   NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
optimized   deployment.apps/cpu-usage   0/1     0            0           2m56s
```

### The issue
At this time, the workload should be cleaned from cluster1. But if we check cluster 1, it remains there.
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kc ws root:espw:kvtwgwtegxp72b72-mb-8efe1aeb-d0bd-4f2c-a48b-d955f33ed002
Current workspace is "root:espw:kvtwgwtegxp72b72-mb-8efe1aeb-d0bd-4f2c-a48b-d955f33ed002".
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get ns
NAME                                STATUS   AGE
argocd                              Active   190d
default                             Active   192d
kcp-edge-syncer-cluster1-1ek2thys   Active   119m
kube-node-lease                     Active   192d
kube-public                         Active   192d
kube-system                         Active   192d
local-path-storage                  Active   192d
optimized                           Active   117m
turbonomic                          Active   190d
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl -n optimized get deploy
NAME        READY   UP-TO-DATE   AVAILABLE   AGE
cpu-usage   1/1     1            1           14m
```

Although the syncer config has been emptied:
```
ubuntu@ip-172-31-31-125:~/edge-mc$ kubectl get syncerconfig the-one -oyaml && kubectl get ns,deployment -A
apiVersion: edge.kcp.io/v1alpha1
kind: SyncerConfig
metadata:
  annotations:
    kcp.io/cluster: 3597eq3gqxel82mx
  creationTimestamp: "2023-04-21T15:34:17Z"
  generation: 32
  name: the-one
  resourceVersion: "4233"
  uid: 36c0166e-e21c-4379-a63d-ce928575a058
spec:
  namespaceScope: {}
status: {}
NAME        STATUS   AGE
default     Active   5h50m
optimized   Active   118m
Error from server (NotFound): Unable to list "apps/v1, Resource=deployments": the server could not find the requested resource (get deployments.apps)
```

### Expected Behaviour

See the section above.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yana1205**
## Summary
- Enhance Edge Syncer to delete objects removed from SyncerConfig
- Add a test case for https://github.com/kcp-dev/edge-mc/issues/326 to E2E 

## Related issue(s)

Fixes #326

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@yana1205 : it would help if you told us where to find container images for the fixed syncer. It would help even more if there were instructions on how to build those.

**Comment by waltforme** [comment]
I tested this PR by
- reinstalling edge syncers using image `ghcr.io/yana1205/edge-mc/syncer:dev-2023-04-24`;
- repeating the steps documented in #326.

I believe the deletion of workload is correctly working now.

/lgtm

BTW Yana mentioned the image in [his comment](https://github.com/kcp-dev/edge-mc/issues/326#issuecomment-1519166349) on #326. @MikeSpreitzer

**Comment by waltforme** [comment]
@yana1205 Thanks for the prompt fix!

**Comment by yana1205** [comment]
> It would help even more if there were instructions on how to build those.

@MikeSpreitzer 
Sure. I updated the doc in the PR https://github.com/kcp-dev/edge-mc/pull/332

**Comment by MikeSpreitzer** [comment]
Thanks for this fix!

**Pull request merged**
