### PR TITLE
✨ Allow multiple sync configs

### PR DESCRIPTION
**Pull request by yana1205**
## Summary
Support multiple EdgeSyncConfigs.
So far EdgeSyncer watches only EdgeSyncConfig that is same name as the name specified in `kubectl kcp workload edge-sync <name> ...`  but since this change, EdgeSyncer supports multiple EdgeSyncConfigs in the sync target workspace. Users can create or separate EdgeSyncConfigs.

FYI @francostellari 
 
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by yana1205** [comment]
Pushed another fix since I sometimes see test failure due to the race detection.
```
$ make e2e-test-edge-syncer KCP_BIN_DIR=$HOME/git/trl/kcp/kcp-dev/bin
...
NO_GORUN=1 GOOS=darwin GOARCH=arm64 go test -race ./test/e2e/edgesyncer/... --kcp-kubeconfig /Users/yana/git/trl/kcp/kcp-edge-mc/.kcp/admin.kubeconfig --suites edge-syncer


...
WARNING: DATA RACE
Read at 0x00c000e31290 by goroutine 431:
  runtime.mapaccess1()
      /opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/map.go:395 +0x26c
  github.com/kcp-dev/edge-mc/pkg/syncer/syncers.getClients()
      /Users/yana/git/trl/kcp/kcp-edge-mc/pkg/syncer/syncers/common.go:145 +0x52c
  github.com/kcp-dev/edge-mc/pkg/syncer/syncers.(*UpSyncer).getClients()
      /Users/yana/git/trl/kcp/kcp-edge-mc/pkg/syncer/syncers/upsyncer.go:71 +0x23c
...
    testing.go:1446: race detected during execution of test
FAIL
FAIL    github.com/kcp-dev/edge-mc/test/e2e/edgesyncer  30.038s
FAIL
make: *** [e2e-test-edge-syncer] Error 1
```
With this fix, at least I haven't seen the above race detection.

**Comment by yana1205** [comment]
I'm not so sure who I should set reviewers. I added Ezra and Mike.

**Review by MikeSpreitzer — COMMENTED** [review]
Why is this change needed?
Where is the documentation of how the syncer is told which configs to watch?

**Comment by yana1205** [comment]
@MikeSpreitzer 
Because users may deploy another EdgeSyncConfig with a different name than the default name specified at running `kcp workload edge-sync <name>` command. (Let me call it "default name". Excuse me if "default name" is not correct word in this context. )
Actually, while @francostellari was working on syncing MVI resources by Edge Syncer, he encountered an issue that nothing is synced due to deploying EdgeSyncConfig with different name ("mvi") from the default name (the default name is likely selected as cluster name like "jetson-nano1"). 
I was also working on similar stuff for C2P and I noticed that it is more convenient to have multiple EdgeSyncConfigs than managing a single one. For example, when C2P receives 2 CRs for compliance A and B, it is easier to manage EdgeSyncConfig per CR. 
Since mailbox workspace and physical cluster is 1:1, I thought that Edge Syncer can watch and consume all EdgeSyncConfigs in the workspace and the decision to which resources are synced are done by the merged configs.
If my understanding is correct, ultimately, Placement Translator will create EdgeSyncConfig from EdgePlacement rather than distributing EdgeSyncConfig from workload management workspace to mailboxes as one of workloads. In that case, I think it's convenient to have multiple EdgeSyncConfigs (maybe EdgeSyncConfig per Placement).

>  Where is the documentation of how the syncer is told which configs to watch?

Here is about EdgeSyncConfig: https://docs.kcp-edge.io/docs/coding-milestones/poc2023q1/edge-syncer/#edgesyncconfig but the detail how the syncer is told which configs to watch was not there yet at that time.

**Review by MikeSpreitzer — APPROVED** [review]
The plan is for the placement translator to maintain one syncer config in each mailbox workspace.  The placement translator will merge the effects of all the EdgePlacement objects that are relevant to a given mailbox workspace.

More importantly, the syncer is a process that is launched as part of the bootstraping of the edge cluster.  The syncer has to be told what config to watch before any EdgePlacement objects exist, and that instruction has to remain correct as EdgePlacement objects are created, updated, and deleted.

If you find it convenient, for interim purposes, to make it possible to configure the edge syncer to watch multiple configs then that is OK.  As noted above, as far as I can see, that will not be needed once we have the placement translator working.

Do please document how the edge syncer is told what config(s) to watch.

/lgtm

**Comment by yana1205** [comment]
> More importantly, the syncer is a process that is launched as part of the bootstraping of the edge cluster. The syncer has to be told what config to watch before any EdgePlacement objects exist, and that instruction has to remain correct as EdgePlacement objects are created, updated, and deleted.

Yes, the current Edge Syncer is working as that. Edge Syncer will watch an EdgeSyncConfig that's created in a workspace at EdgeSyncer registration command for workspace. 
The flow is as follows:
1. Run `kubectl kcp workload edge-syncer <name>` to make EdgeSyncer available in a workspace
  1. The command generates bootstrap manifests to install EdgeSyncer in pcluster
  2. The command also creates EdgeSyncConfig with "<name>".
1. Apply the bootstrap manifests on a pcluster
  1. EdgeSyncer watches EdgeSyncConfig named "<name>"
  2. With this PR, EdgeSyncer will watch all EdgeSyncConfig in the workspace

> Do please document how the edge syncer is told what config(s) to watch.

Sure, I'll update https://docs.kcp-edge.io/docs/coding-milestones/poc2023q1/edge-syncer/#edgesyncconfig with the detail about how the edge syncer is told what config(s) to watch.

**Pull request merged**
