### PR TITLE
:book: Improve punctuation for list items in README

### LINKED ISSUE #23: Issues with README.md
We need consistent punctuation for list items. [This post](https://intelligentediting.com/blog/how-to-punctuate-bulleted-and-numbered-lists/) has some suggestions.

We don't have a 'developer guides' document but the README.md mentions it. Should we remove the link, or create such a guide then fix the link?

### PR DESCRIPTION
**Pull request by waltforme**
## Summary

No matter which convention we use, at least there should be a full stop at the end of a list.

## Related issue(s)

Fixes #23

### CODE REVIEW

**Comment by ezrasilvera** [comment]
This file was copied from kcp-dev/kcp. Maybe you want to open a PR against KCP and after merging there we can re-sync?

**Comment by waltforme** [comment]
> This file was copied from kcp-dev/kcp. Maybe you want to open a PR against KCP and after merging there we can re-sync?

hmm, I just checked again, these contents are edge specific right? I didn't find these contents in kcp-dev/kcp.

**Comment by ezrasilvera** [comment]
test bot
/lgtm

**Pull request merged**
