### PR TITLE
:sparkles: Update the syncer image registry in kubectl-kubestellar-prep_script

### PR DESCRIPTION
**Pull request by francostellari**
## Summary

Point to the new quay.io registetry

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by francostellari** [comment]
@MikeSpreitzer 
@clubanderson

**Comment by MikeSpreitzer** [comment]
Is that thing not freely available?

```console\]
(base) mspreitz@mjs12 kcp % docker pull quay.io/kubestellar/syncer:v0.2.0
Trying to pull quay.io/kubestellar/syncer:v0.2.0...
Error: initializing source docker://quay.io/kubestellar/syncer:v0.2.0: unable to retrieve auth token: invalid username/password: unauthorized: Invalid Username or Password
```

**Comment by MikeSpreitzer** [comment]
```console
(base) mspreitz@mjs12 kcp % docker pull quay.io/kubestellar/syncer:v0.2.0
Trying to pull quay.io/kubestellar/syncer:v0.2.0...
Error: initializing source docker://quay.io/kubestellar/syncer:v0.2.0: unable to retrieve auth token: invalid username/password: unauthorized: Invalid Username or Password
(base) mspreitz@mjs12 kcp % grep quay ~/.docker/config.json
(base) mspreitz@mjs12 kcp % 
```

**Comment by francostellari** [comment]
@MikeSpreitzer it was waiting for @clubanderson to push the image in quay. He just did it can you please check again now?

**Comment by MikeSpreitzer** [comment]
```console
(base) mspreitz@mjs12 kcp % podman logout quay.io
Removed login credentials for quay.io

(base) mspreitz@mjs12 kcp % docker pull quay.io/kubestellar/syncer:v0.2.0
Trying to pull quay.io/kubestellar/syncer:v0.2.0...
Error: initializing source docker://quay.io/kubestellar/syncer:v0.2.0: reading manifest v0.2.0 in quay.io/kubestellar/syncer: unauthorized: access to the requested resource is not authorized
```

**Comment by MikeSpreitzer** [comment]
I can also successfully pull when I _am_ logged into quay.

**Pull request merged**
