### PR TITLE
🌱 Make mailbox controller source consistent with `make imports`

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR re-organizes the imports of the mailbox controller to keep `make impors` happy.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@francostellari you need to become a member of kcp-dev

**Comment by clubanderson** [comment]
@francostellari and @kproche are now members of the kcp and kcp-edge contributors groups.

**Review by francostellari — APPROVED** [review]

**Review by francostellari — APPROVED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
Well whaddaya know, `make imports` is _not_ idempotent!
https://github.com/openshift-eng/openshift-goimports/issues/16

**Pull request merged**
