### PR TITLE
📖 EMC syncer developers do not know all the kinds of objects

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR extends the list of distinctive features of the EMC syncer to note that the kinds of objects to sync are not all known at development time.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by pdettori** [comment]
Doesn't the current TMC syncer already offer the ability to configure the resources to sync at deployment time ? If this is the case, why do we need to make this distinction here ?

**Comment by MikeSpreitzer** [comment]
I realize that the TMC syncer is configured with a set of resources to sync.  The question is whether a user can configure the syncing of a resource that the developers did not prepare the syncer for.  Do you know?

**Comment by pdettori** [comment]
My understanding is that they have mutators for deployment, and perhaps pods. But in general you should be able to configure resources to sync at deployment time for namespaced resources. For non-namespaced resources, it's a different story, as those currently are supported writing code.

**Comment by MikeSpreitzer** [comment]
I got testimony today from people who got the TMC syncer to sync custom resources not known to the TMC developers.

**Pull request closed without merging**
