### PR TITLE
🌱 Better names for ClientOpts methods

### PR DESCRIPTION
**Pull request by waltforme**
## Summary
This PR gives better names to ClientOpts' methods. Thanks to @MikeSpreitzer 's suggestions.

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
Thanks.

FYI, for a more extensive thing like this, see https://github.com/kubernetes/cli-runtime/blob/master/pkg/genericclioptions/config_flags.go .  Note that there are many other settings that a `main` might want to provide default values for.

**Comment by waltforme** [comment]
> FYI, for a more extensive thing like this, see https://github.com/kubernetes/cli-runtime/blob/master/pkg/genericclioptions/config_flags.go . Note that there are many other settings that a `main` might want to provide default values for.

I see. Thanks for the info!

**Comment by waltforme** [comment]
Oh sorry, fixed in force-push to 2d3853e. @MikeSpreitzer

**Pull request merged**
